version: '3.4'
services:
  rental:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      target: run
    env_file: ../.env
    ports:
      - published: 9001
        target: 9000
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - MYSQL_HOST=mysql
      - STORAGE_PATH=/OpenClassrooms/Rental
    volumes:
      - rental_data:/OpenClassrooms/Rental
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    env_file: ../.env
    ports:
      - published: 3306
        target: 3306
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 20
  adminer:
    image: adminer
    restart: always
    ports:
      - published: 8080
        target: 8080
volumes:
  mysql_data:
  rental_data: