version: '3.1'

services:
  mysql:
    image: mysql:8.1
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: db_rental
      MYSQL_USER: springuser
      MYSQL_PASSWORD: ThePassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
volumes:
  mysql_data: