version: '3.1'
services:
  mysql:
    image: mysql:8.1
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    env_file: ../.env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - "9000:8080"
volumes:
  mysql_data: